#!/usr/bin/env python3
"""
BugWolf Formal Verification Bridge v1.0.0

Converts smart contract findings into formal verification harnesses:
  1. Certora spec generation (CVL — Certora Verification Language)
  2. Medusa/Echidna fuzz harness generation (Solidity)
  3. Foundry invariant test generation
  4. Automatic execution and result parsing
  5. Formal proof embedding in reports

Also supports Web2 findings:
  - API schema fuzzing (schemathesis)
  - Auth policy verification (custom)

Usage:
  python3 tools/formal_verify.py --finding-file findings.jsonl
  python3 tools/formal_verify.py --target example.com --mode web
  python3 tools/formal_verify.py --target ContractName --mode solidity
  python3 tools/formal_verify.py --run --harness generated/Certora.spec
"""

import os
import sys
import json
import subprocess
import tempfile


def _sandboxed(cmd, **kw):
    """Spawn through the subprocess sandbox (kill switch + allowlist + env
    scrub); certoraRun/echidna/halmos are operator-granted Web3 tools."""
    from tools.runtime.sandbox import sandboxed_run
    return sandboxed_run([str(c) for c in cmd], cwd=os.getcwd(),
                         purpose="formal_verify", **kw)
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional, Dict, List, Any
from dataclasses import dataclass, field, asdict

try:
    from tools.runtime_paths import CODE_ROOT, workspace_root
except ImportError:  # direct script execution
    from runtime_paths import CODE_ROOT, workspace_root

ROOT = workspace_root()
sys.path.insert(0, str(CODE_ROOT))

VERIFY_DIR = ROOT / "verify"


# ---------------------------------------------------------------------------
# Certora CVL Spec Generator
# ---------------------------------------------------------------------------

def generate_certora_spec(finding: Dict) -> str:
    """Generate a Certora Verification Language (CVL) specification
    that proves a vulnerability either exists or has been fixed.

    CVL is used with Certora Prover to formally verify smart contracts.
    """
    contract = finding.get("contract_or_program", finding.get("target", "Target"))
    function_name = finding.get("function", "vulnerableFunction")
    invariant = finding.get("invariant_broken", "")
    bug_class = finding.get("bug_class", "unknown")
    severity = finding.get("severity", "medium")

    # Map bug class to CVL rule type
    rule_map = {
        "reentrancy": "noReentrancy",
        "access-control-bypass": "accessControl",
        "integer-overflow": "noOverflow",
        "precision-loss": "precisionCheck",
        "oracle-manipulation": "oracleIntegrity",
        "flash-loan-attack": "flashLoanResistant",
        "signature-replay": "noReplay",
        "race-condition-sc": "atomicity",
    }

    rule_name = rule_map.get(bug_class, "invariantCheck")

    spec = f"""\
/*
 * Certora CVL Specification
 * Generated by BugWolf Formal Verification Bridge v1.0.0
 * Target: {contract}
 * Finding: {finding.get('title', 'Untitled')}
 * Severity: {severity}
 *
 * To run:
 *   certoraRun {contract}.sol --verify {contract}:certora/{contract}.spec
 */

using {contract} as target;

/*
 * METHODS: List all public/external functions to include in verification
 */
methods {{
    // Add all public/external function signatures here
    // function {function_name}(uint256 amount) external returns (bool);
}}

/*
 * RULE: {rule_name}
 * Invariant: {invariant}
 *
 * If this rule is violated, the vulnerability exists.
 * After a fix is applied, this rule should pass.
 */
rule {rule_name}(method f) {{
    env e;
    calldataarg args;

    // Pre-conditions
    // e.g., require target.balanceOf(e.msg.sender) > 0;

    // Capture pre-state
    uint256 balanceBefore = target.balanceOf(e.msg.sender);
    uint256 totalSupplyBefore = target.totalSupply();

    // Execute any public function
    f(e, args);

    // Post-condition: the invariant must hold
    // Customize based on the finding:
    assert balanceBefore <= target.balanceOf(e.msg.sender)
        , "Balance should never decrease without transfer";
    assert totalSupplyBefore == target.totalSupply()
        , "Total supply should remain constant";
}}

/*
 * RULE: noPrivilegeEscalation
 * Verifies that non-admin accounts cannot call privileged functions.
 */
rule noPrivilegeEscalation(method f) {{
    env e;
    calldataarg args;

    // Sender is NOT the owner/admin
    require e.msg.sender != target.owner();

    // Try to call any function
    f(e, args);

    // Phase 0 H-10: require an actual admin-state change was attempted.
    // The previous assertion target.owner() == e.msg.sender || target.owner()
    // != e.msg.sender was a tautology (always true) and was being persisted
    // as a verification artifact. Now we assert that the post-call owner
    // equals the caller (which would be the escalation) AND that the caller
    // is non-owner pre-condition.
    assert e.msg.sender != target.owner() => target.owner() == e.msg.sender
        , "Non-owner changed admin state";
}}

/*
 * RULE: invariant_totalSupply
 * Generic invariant check — customize per finding.
 */
rule invariant_check() {{
    // Define pre-conditions and post-conditions
    // This is a template — fill in based on finding.attack_path
    assert true;
}}
"""
    return spec


# ---------------------------------------------------------------------------
# Medusa / Echidna Fuzz Harness Generator
# ---------------------------------------------------------------------------

def generate_fuzz_harness(finding: Dict, framework: str = "foundry") -> str:
    """Generate a fuzzing harness that tries to break the invariant.

    Supports Foundry (Echidna-compatible) and Medusa format.
    """
    contract = finding.get("contract_or_program", finding.get("target", "Target"))
    invariant = finding.get("invariant_broken", "")
    bug_class = finding.get("bug_class", "unknown")
    title = finding.get("title", "Finding").replace(" ", "")

    if framework == "foundry":
        harness = f"""\
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.19;

import "../src/{contract}.sol";

/// @title Fuzz Harness: {title}
/// @notice Proves or disproves: {invariant}
/// @custom:generated BugWolf Formal Verification Bridge v1.0.0
///
/// Run with:
///   echidna {title}Harness.sol --contract {title}Harness --config echidna.yaml
///   medusa fuzz --target contracts/harness/{title}Harness.sol

contract {title}Harness {{
    {contract} target;

    constructor() {{
        target = new {contract}();
    }}

    // ================================================================
    // Helper functions — call any target function
    // ================================================================

    function callTarget(bytes memory data) public returns (bool) {{
        (bool success, ) = address(target).call(data);
        return success;
    }}

    // ================================================================
    // Invariants to check (Echidna/Medusa will call these)
    // Functions starting with "echidna_" or "invariant_" are assertions
    // ================================================================

    /// @custom:invariant {invariant}
    function echidna_invariant() public view returns (bool) {{
        // TODO: Encode the invariant as a boolean check
        // Example: return target.totalSupply() <= target.MAX_SUPPLY();
        return true;
    }}

    /// @custom:invariant No unauthorized role changes
    function echidna_noPrivilegeEscalation() public view returns (bool) {{
        // TODO: Check that admin/owner hasn't changed unexpectedly
        return true;
    }}

    /// @custom:invariant Balances sum to totalSupply
    function echidna_balanceSum() public view returns (bool) {{
        // TODO: sum of all balances == totalSupply
        return true;
    }}
}}
"""
    elif framework == "medusa":
        harness = f"""\
# Medusa Fuzzing Configuration
# Generated by BugWolf v1.0.0
# Target: {contract}
# Finding: {title}

fuzzing:
  workers: 4
  testLimit: 50000
  callSequenceLength: 100
  shrinkLimit: 5000
  coverage: true

  # Corpus directory for interesting inputs
  corpusDirectory: medusa-corpus-{title.lower()}

  # Deployer address (has initial balance)
  deployer: "0x30000"
  senderAddresses:
    - "0x10000"
    - "0x20000"
    - "0x30000"

sequences:
  # Custom sequence that targets the vulnerable function
  - name: "exploit_{bug_class}"
    calls:
      - target.function_{bug_class}()
      - wait: 1
      - target.function_{bug_class}()
"""
    else:
        harness = f"// Unknown framework: {framework}"

    return harness


# ---------------------------------------------------------------------------
# Web API Schema Fuzzing (schemathesis)
# ---------------------------------------------------------------------------

def generate_api_schema_test(endpoint: str, method: str,
                              finding: Dict) -> str:
    """Generate a schemathesis-compatible test for API findings.

    Schemathesis auto-generates test cases from OpenAPI schemas.
    This generates a targeted test for a specific finding.
    """
    return f"""\
# API Schema Fuzz Test
# Generated by BugWolf v1.0.0
# Target: {method} {endpoint}
# Finding: {finding.get('title', 'Untitled')}
#
# Run with:
#   schemathesis run --base-url={endpoint.split('/api')[0]} \\
#       -A '{finding.get('parameter', '')}' \\
#       --hypothesis-max-examples=1000

import schemathesis
import pytest

schema = schemathesis.from_uri("{endpoint.split('/api')[0]}/openapi.json")

@schema.parametrize()
def test_api_invariant(case):
    \"\"\"Test that the API maintains security invariants.\"\"\"
    response = case.call()

    # Check 1: No information disclosure
    assert "password" not in response.text.lower()
    assert "secret" not in response.text.lower()
    assert "token" not in response.text.lower()

    # Check 2: Auth required for sensitive endpoints
    if "/admin" in case.operation.path or "/internal" in case.operation.path:
        assert response.status_code in (401, 403), \\
            f"Admin endpoint returned {{response.status_code}}"

    # Check 3: No mass assignment
    if case.operation.method in ("POST", "PUT", "PATCH"):
        response = case.call(extra_headers={{"X-Test-Role": "admin"}})
        if response.status_code == 200:
            # Verify role header wasn't actually applied
            pass
"""
    return ""


# ---------------------------------------------------------------------------
# Harness executor
# ---------------------------------------------------------------------------

def run_certora(spec_path: str, contract_path: str) -> Dict:
    """Run Certora Prover on a generated spec."""
    if not shutil.which("certoraRun"):
        return {"success": False, "error": "certoraRun not installed"}

    try:
        result = _sandboxed(
            ["certoraRun", contract_path,
             "--verify", f"{Path(contract_path).stem}:{spec_path}"],
            text=True, timeout=600)

        # Parse Certora output
        output = result.stdout
        violations = "violated" in output.lower()
        passed = "successfully" in output.lower() and not violations

        return {
            "success": result.returncode == 0,
            "passed": passed,
            "violations_found": violations,
            "stdout": output[-2000:],
            "stderr": result.stderr[-500:],
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "Certora timeout (600s)"}
    except Exception as e:
        return {"success": False, "error": str(e)}


def run_echidna(harness_path: str) -> Dict:
    """Run Echidna fuzzer on a harness."""
    if not shutil.which("echidna"):
        return {"success": False, "error": "echidna not installed"}

    try:
        result = _sandboxed(
            ["echidna", harness_path, "--contract",
             Path(harness_path).stem],
            text=True, timeout=600)

        # Parse Echidna output for invariant violations
        output = result.stdout + result.stderr
        violations = []
        for line in output.splitlines():
            if "violated" in line.lower() or "FAIL" in line:
                violations.append(line.strip())

        return {
            "success": result.returncode == 0,
            "violations": violations,
            "violations_count": len(violations),
            "output": output[-2000:],
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "Echidna timeout (600s)"}
    except Exception as e:
        return {"success": False, "error": str(e)}


# ---------------------------------------------------------------------------
# Main bridge logic
# ---------------------------------------------------------------------------

class FormalVerifyBridge:
    """Bridges findings to formal verification tools."""

    def __init__(self):
        VERIFY_DIR.mkdir(parents=True, exist_ok=True)
        (VERIFY_DIR / "certora").mkdir(exist_ok=True)
        (VERIFY_DIR / "echidna").mkdir(exist_ok=True)
        (VERIFY_DIR / "medusa").mkdir(exist_ok=True)
        (VERIFY_DIR / "api").mkdir(exist_ok=True)

    def generate_all(self, findings: List[Dict]) -> Dict:
        """Generate verification harnesses for all findings.

        Returns summary of generated artifacts.
        """
        results = {
            "total": len(findings),
            "certora_specs": 0,
            "fuzz_harnesses": 0,
            "api_tests": 0,
            "artifacts": [],
            "errors": [],
        }

        for finding in findings:
            bug_class = finding.get("bug_class", "")
            is_sc = finding.get("chain") or finding.get("contract_or_program")

            try:
                if is_sc:
                    # Smart contract finding → Certora + Fuzz
                    if bug_class in ("reentrancy", "access-control-bypass",
                                     "integer-overflow", "oracle-manipulation",
                                     "flash-loan-attack"):
                        spec = generate_certora_spec(finding)
                        fid = finding.get("finding_id", "unknown")[:8]
                        spec_path = VERIFY_DIR / "certora" / f"{fid}.spec"
                        spec_path.write_text(spec)
                        results["certora_specs"] += 1
                        results["artifacts"].append({
                            "type": "certora_spec",
                            "finding_id": fid,
                            "path": str(spec_path),
                        })

                    harness = generate_fuzz_harness(finding, "foundry")
                    fid = finding.get("finding_id", "unknown")[:8]
                    harness_path = VERIFY_DIR / "echidna" / f"{fid}Harness.sol"
                    harness_path.write_text(harness)
                    results["fuzz_harnesses"] += 1
                    results["artifacts"].append({
                        "type": "fuzz_harness",
                        "finding_id": fid,
                        "path": str(harness_path),
                    })

                else:
                    # Web/API finding
                    endpoint = finding.get("endpoint", "")
                    method = finding.get("method", "GET")
                    if endpoint and "/api" in endpoint:
                        test = generate_api_schema_test(endpoint, method, finding)
                        fid = finding.get("finding_id", "unknown")[:8]
                        test_path = VERIFY_DIR / "api" / f"{fid}_test.py"
                        test_path.write_text(test)
                        results["api_tests"] += 1
                        results["artifacts"].append({
                            "type": "api_schema_test",
                            "finding_id": fid,
                            "path": str(test_path),
                        })

            except Exception as e:
                results["errors"].append({
                    "finding_id": finding.get("finding_id", "?"),
                    "error": str(e),
                })

        return results

    def run_verification(self, artifact_path: str, artifact_type: str) -> Dict:
        """Execute a verification artifact."""
        if artifact_type == "certora_spec":
            # Need the contract path too
            return {"success": False, "error": "Contract path required for Certora"}
        elif artifact_type == "fuzz_harness":
            return run_echidna(artifact_path)
        else:
            return {"success": False, "error": f"Unknown artifact type: {artifact_type}"}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="BugWolf Formal Verification Bridge")
    parser.add_argument("--finding-file", help="JSONL file with findings")
    parser.add_argument("--finding-id", help="Single finding ID")
    parser.add_argument("--target", help="Target name to load findings from state")
    parser.add_argument("--generate-only", action="store_true",
                        help="Generate harnesses without running")
    parser.add_argument("--run", help="Run verification on a harness")
    parser.add_argument("--type", help="Artifact type for --run",
                        choices=["certora_spec", "fuzz_harness", "api_test"])
    parser.add_argument("--framework", default="foundry",
                        choices=["foundry", "medusa"],
                        help="Fuzzing framework (default: foundry)")
    args = parser.parse_args()

    bridge = FormalVerifyBridge()

    # Load findings
    findings = []
    if args.finding_file:
        raw = Path(args.finding_file).read_text()
        findings = [json.loads(l) for l in raw.splitlines() if l.strip()]
    elif args.target:
        try:
            from tools.state import get_findings
            findings = get_findings(args.target)
        except ImportError:
            print("[!] state module not available")
            sys.exit(1)
    elif args.finding_id:
        findings = [{"finding_id": args.finding_id, "title": "Manual"}]

    if not findings and not args.run:
        print("[!] No findings loaded")
        sys.exit(1)

    if args.run:
        result = bridge.run_verification(args.run, args.type or "fuzz_harness")
        print(json.dumps(result, indent=2))

    else:
        print(f"[*] BugWolf Formal Verification Bridge v1.0.0")
        print(f"[*] Processing {len(findings)} finding(s)...")

        results = bridge.generate_all(findings)

        print(f"\n[*] Generated:")
        print(f"    Certora specs:  {results['certora_specs']}")
        print(f"    Fuzz harnesses: {results['fuzz_harnesses']}")
        print(f"    API tests:      {results['api_tests']}")

        if results["errors"]:
            print(f"\n[!] Errors:")
            for e in results["errors"]:
                print(f"    [{e['finding_id']}] {e['error']}")

        if results["artifacts"]:
            print(f"\n[*] Artifacts:")
            for a in results["artifacts"]:
                print(f"    [{a['type']}] {a['path']}")


if __name__ == "__main__":
    main()
