#!/usr/bin/env python3
"""BugWolf fuzz engine v1.24.1+ — coverage-guided fuzzing harness generator.

Generates ready-to-run harnesses for:
  - libFuzzer (LLVM)         → C/C++/Rust targets
  - AFL++                    → C/C++ targets with AFL instrumentation
  - Honggfuzz                → C/C++/Rust targets
  - Python atheris           → Python targets
  - Boofuzz                  → network protocol targets (block-based)
  - Schemathesis             → OpenAPI/GraphQL schema fuzzing
  - foundry fuzz             → Solidity invariants
  - Echidna                  → Solidity properties

The generator does NOT run the fuzzer itself — it scaffolds the harness
and the build script. Operators run the actual fuzzer outside BugWolf.

Usage:
  python3 tools/fuzz_engine.py --target some-target --lang rust \
      --entry-fn fuzz_target --output fuzz/
  python3 tools/fuzz_engine.py --target some-target --engine schemathesis \
      --spec openapi.json --output fuzz/
  python3 tools/fuzz_engine.py --target some-contract --engine foundry \
      --contract Contract.sol --output fuzz/

Each generated harness ships with:
  - The source file (or build instructions)
  - corpus/ seed inputs
  - crash/ output dir
  - run.sh that operators invoke after `cargo install` / `pip install`
  - a JSONL evidence file the mission_runner can read back

This module is offline-by-design: no network, no LLM. It only writes files.
"""
from __future__ import annotations

import json
import os
import sys
import textwrap
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


SCHEMA = "bugwolf-fuzz-engine/v1"

# Engines BugWolf can scaffold.
ENGINES = {
    "libfuzzer": "LLVM libFuzzer (C/C++/Rust)",
    "afl":       "AFL++ (C/C++)",
    "honggfuzz": "Honggfuzz (C/C++/Rust)",
    "atheris":   "Atheris (Python)",
    "boofuzz":   "Boofuzz (network protocols)",
    "schemathesis": "Schemathesis (OpenAPI/GraphQL)",
    "foundry":   "Foundry invariant fuzzer (Solidity)",
    "echidna":   "Echidna property tester (Solidity)",
    "medusa":    "Medusa (Solidity)",
}

LANGUAGES = {"c", "cpp", "rust", "python", "solidity", "go"}


@dataclass
class FuzzTarget:
    name: str
    engine: str
    language: str
    entry: Optional[str] = None
    source: Optional[str] = None
    contract: Optional[str] = None
    spec: Optional[str] = None
    seeds: List[str] = field(default_factory=list)
    options: Dict[str, Any] = field(default_factory=dict)


@dataclass
class FuzzHarness:
    target: str
    engine: str
    files: Dict[str, str] = field(default_factory=dict)  # path -> content
    manifest: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Engine templates
# ---------------------------------------------------------------------------

LIBFUZZER_C = r'''// Auto-generated by BugWolf fuzz_engine.py (libFuzzer, C target).
// Build: clang -fsanitize=fuzzer,address -g harness.c -o harness
// Run:   ./ harness corpus/ -max_len=4096 -timeout=5

#include <stdint.h>
#include <stddef.h>

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    if (size == 0) return 0;
    // TODO: replace with the call into the target under test.
    // The function should be deterministic, side-effect-free, and
    // crash/assert on malformed input.
    return 0;
}
'''

LIBFUZZER_RUST = r'''#![no_main]
// Auto-generated by BugWolf fuzz_engine.py (libFuzzer, Rust target).
// Build: cargo fuzz build -F fuzz_<NAME>
// Run:   cargo fuzz run fuzz_<NAME>

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    if data.is_empty() { return; }
    // TODO: invoke the target under test.
});
'''

AFL_C = r'''// Auto-generated by BugWolf fuzz_engine.py (AFL++, C target).
// Build: afl-clang-fast -g harness.c -o harness
// Run:   afl-fuzz -i corpus/ -o crashes/ -- ./harness @@

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s <file>\n", argv[0]); return 1; }
    FILE *f = fopen(argv[1], "rb");
    if (!f) return 1;
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    unsigned char *buf = (unsigned char*)malloc(n);
    fread(buf, 1, n, f);
    fclose(f);
    // TODO: invoke the target under test with `buf` / `n`.
    free(buf);
    return 0;
}
'''

ATHERIS_PYTHON = r'''# Auto-generated by BugWolf fuzz_engine.py (Atheris, Python target).
# Install: pip install atheris
# Run:     python harness.py corpus/

import sys
import atheris

with atheris.instrument_imports():
    import target_module  # TODO: import the target under test


def TestOneInput(data: bytes):
    if not data:
        return
    # TODO: invoke the target with parsed `data`.
    fdp = atheris.FuzzedDataProvider(data)
    # Example: text = fdp.ConsumeUnicodeNoSurrogates(64)


if __name__ == "__main__":
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()
'''

BOOFUZZ_PYTHON = r'''# Auto-generated by BugWolf fuzz_engine.py (Boofuzz, network protocol).
# Install: pip install boofuzz
# Run:     python harness.py

from boofuzz import Session, Request, Static, String
# TODO: define Request primitives for the target protocol.


def main():
    session = Session(target=Target(connection=SocketConnection("127.0.0.1", 80)))
    # TODO: define define_request() and session.fuzz() calls.
    session.fuzz()


if __name__ == "__main__":
    main()
'''

SCHEMATHESIS_PYTHON = r'''# Auto-generated by BugWolf fuzz_engine.py (Schemathesis, OpenAPI/GraphQL).
# Install: pip install schemathesis
# Run:     st run --checks all openapi.json

# Schemathesis is a CLI; no Python harness needed.
# Save your spec as openapi.json, then:
#   st run --checks all --max-examples=1000 openapi.json
# Or for stateful testing:
#   st run --checks all --stateful=links openapi.json
'''

FOUNDRY_SOLIDITY = r'''// Auto-generated by BugWolf fuzz_engine.py (Foundry invariant fuzzer).
// Run in the target's Foundry project:
//   forge test --match-contract Harness -vvv

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";

contract Harness is Test {
    // TODO: import the target contract under test.

    function setUp() public {
        // TODO: deploy target.
    }

    /// @notice Always-passing invariant; replace with the bug surface.
    function invariant_never_reverts() public view {
        assertTrue(true);
    }

    /// @notice Foundry fuzz entrypoint — call any target function.
    function testFuzz_targetEntry(uint256 amount, address to) public {
        amount = bound(amount, 0, 1e30);
        // TODO: invoke target function with fuzzed inputs.
    }
}
'''

ECHIDNA_SOLIDITY = r'''// Auto-generated by BugWolf fuzz_engine.py (Echidna).
// Run:   echidna-test Harness.sol --contract Harness

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract Harness {
    // TODO: import the target contract under test.

    /// echidna_<name>: always-passing; replace with the bug surface.
    function echidna_invariant_never_reverts() public view returns (bool) {
        return true;
    }
}
'''


def _libfuzzer(target: FuzzTarget) -> FuzzHarness:
    files: Dict[str, str] = {}
    if target.language in ("c", "cpp"):
        files["harness.c"] = LIBFUZZER_C
        files["build.sh"] = (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "clang -fsanitize=fuzzer,address -g harness.c -o harness\n"
        )
    elif target.language == "rust":
        files["src/fuzz_target.rs"] = LIBFUZZER_RUST.replace("<NAME>", target.name)
        files["Cargo.toml"] = textwrap.dedent('''\
            [package]
            name = "fuzz-target"
            version = "0.0.0"
            edition = "2021"

            [dependencies]
            libfuzzer-sys = "0.4"

            [[bin]]
            name = "fuzz_target"
            path = "src/fuzz_target.rs"
        ''')
        files["build.sh"] = (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "rustc -C link-arg=-fsanitize=fuzzer \\\n"
            "      -C passes='sancov' \\\n"
            "      src/fuzz_target.rs -o fuzz_target\n"
        )
    files["run.sh"] = (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "mkdir -p crashes\n"
        "./harness corpus/ -artifact_prefix=crashes/ "
        "-max_len=4096 -timeout=5\n"
    )
    files["corpus/.gitkeep"] = ""
    files["crashes/.gitkeep"] = ""
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


def _afl(target: FuzzTarget) -> FuzzHarness:
    files = {
        "harness.c": AFL_C,
        "build.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "AFL_PATH=\"${AFL_PATH:-/usr/local}\"\n"
            "$AFL_PATH/bin/afl-clang-fast -g harness.c -o harness\n"
        ),
        "run.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "AFL_PATH=\"${AFL_PATH:-/usr/local}\"\n"
            "mkdir -p crashes\n"
            "$AFL_PATH/bin/afl-fuzz -i corpus/ -o crashes/ -- ./harness @@\n"
        ),
        "corpus/.gitkeep": "",
        "crashes/.gitkeep": "",
    }
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


def _atheris(target: FuzzTarget) -> FuzzHarness:
    files = {
        "harness.py": ATHERIS_PYTHON,
        "requirements.txt": "atheris\n",
        "run.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "python3 harness.py corpus/\n"
        ),
        "corpus/.gitkeep": "",
    }
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


def _boofuzz(target: FuzzTarget) -> FuzzHarness:
    files = {
        "harness.py": BOOFUZZ_PYTHON,
        "requirements.txt": "boofuzz\n",
        "run.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "python3 harness.py\n"
        ),
    }
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


def _schemathesis(target: FuzzTarget) -> FuzzHarness:
    files = {
        "README.md": SCHEMATHESIS_PYTHON,
        "run.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "st run --checks all --max-examples=1000 "
            + (target.spec or "openapi.json") + "\n"
        ),
        "st.toml": textwrap.dedent('''\
            [project]
            name = "bugwolf-schemathesis"

            [harness]
            # schemathesis reads openapi.json from CWD by default
            base_url = "http://localhost:8080"

            [checks]
            enabled = ["all"]
        '''),
        "openapi.json.placeholder": (
            "# Drop your openapi.json here, then run ./run.sh\n"
        ),
    }
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


def _foundry(target: FuzzTarget) -> FuzzHarness:
    files = {
        "test/Harness.t.sol": FOUNDRY_SOLIDITY,
        "run.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "forge test --match-contract Harness -vvv\n"
        ),
        "foundry.toml": textwrap.dedent('''\
            [profile.default]
            src = "src"
            out = "out"
            libs = ["lib/forge-std"]
            solc_version = "0.8.20"

            [fuzz]
            runs = 256
        '''),
        "README.md": (
            "# BugWolf Foundry Fuzz Harness\n\n"
            "Run `./run.sh` (requires `forge` on PATH).\n"
        ),
    }
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


def _echidna(target: FuzzTarget) -> FuzzHarness:
    files = {
        "Harness.sol": ECHIDNA_SOLIDITY,
        "run.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "echidna-test Harness.sol --contract Harness\n"
        ),
        "echidna.yaml": textwrap.dedent('''\
            # Echidna configuration for BugWolf fuzz harness
            coverage: true
            corpusDir: "corpus"
            format: "text"
            '''),
        "README.md": (
            "# BugWolf Echidna Fuzz Harness\n\n"
            "Run `./run.sh` (requires `echidna-test` on PATH).\n"
        ),
    }
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


def _medusa(target: FuzzTarget) -> FuzzHarness:
    files = {
        "Harness.sol": ECHIDNA_SOLIDITY,  # same template
        "medusa.json": json.dumps({
            "fuzzing": {
                "workers": 10,
                "timeout": 0,
                "testLimit": 100000,
            },
            "compilation": {
                "platform": "solc",
                "solcVersion": "0.8.20",
            },
            "targetContracts": ["Harness"],
        }, indent=2),
        "run.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "medusa fuzz\n"
        ),
    }
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


def _honggfuzz(target: FuzzTarget) -> FuzzHarness:
    # Reuse AFL harness with Honggfuzz's compiler wrapper.
    files = {
        "harness.c": AFL_C,
        "build.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "HFUZZ_CC=\"${HFUZZ_CC:-hfuzz-cc}\"\n"
            "$HFUZZ_CC -g harness.c -o harness\n"
        ),
        "run.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "mkdir -p crashes\n"
            "honggfuzz -i corpus/ -- ./harness\n"
        ),
        "corpus/.gitkeep": "",
    }
    return FuzzHarness(target=target.name, engine=target.engine, files=files)


_DISPATCH = {
    "libfuzzer": _libfuzzer,
    "afl": _afl,
    "honggfuzz": _honggfuzz,
    "atheris": _atheris,
    "boofuzz": _boofuzz,
    "schemathesis": _schemathesis,
    "foundry": _foundry,
    "echidna": _echidna,
    "medusa": _medusa,
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate(target: FuzzTarget) -> FuzzHarness:
    """Generate a fuzz harness for the given target."""
    if target.engine not in _DISPATCH:
        raise ValueError(
            f"unknown engine: {target.engine}; "
            f"supported: {', '.join(_DISPATCH.keys())}"
        )
    harness = _DISPATCH[target.engine](target)
    harness.manifest = {
        "schema": SCHEMA,
        "target": target.name,
        "engine": target.engine,
        "language": target.language,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "file_count": len(harness.files),
        "operators": {
            "build": "cd <output> && ./build.sh",
            "run": "cd <output> && ./run.sh",
            "stop_signal": "SIGINT (Ctrl-C) or process kill",
        },
    }
    return harness


def write(harness: FuzzHarness, output_dir: Path) -> Dict[str, Any]:
    """Write the harness files to ``output_dir``. Returns the manifest."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    for rel, content in harness.files.items():
        target = output_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if rel.endswith(".sh"):
            target.write_text(content)
            target.chmod(0o755)
        else:
            target.write_text(content)
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(harness.manifest, indent=2))
    return harness.manifest


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    import argparse
    p = argparse.ArgumentParser(description="BugWolf fuzz harness generator")
    p.add_argument("--target", required=True, help="Target name")
    p.add_argument("--engine", required=True, choices=list(ENGINES.keys()),
                   help="Fuzzing engine")
    p.add_argument("--lang", choices=sorted(LANGUAGES), help="Source language")
    p.add_argument("--entry", help="Entry function (e.g. LLVMFuzzerTestOneInput)")
    p.add_argument("--source", help="Source file path (informational)")
    p.add_argument("--contract", help="Solidity contract (for foundry/echidna)")
    p.add_argument("--spec", help="OpenAPI spec path (for schemathesis)")
    p.add_argument("--output", required=True, help="Output directory")
    p.add_argument("--seed", action="append", default=[],
                   help="Path to a seed corpus file (repeatable)")
    args = p.parse_args()

    target = FuzzTarget(
        name=args.target,
        engine=args.engine,
        language=args.lang or _infer_lang(args),
        entry=args.entry,
        source=args.source,
        contract=args.contract,
        spec=args.spec,
        seeds=args.seed,
    )
    harness = generate(target)
    manifest = write(harness, Path(args.output))
    print(f"[+] Fuzz harness written to {args.output}/")
    print(f"    target={target.name} engine={target.engine} "
          f"language={target.language}")
    print(f"    files={len(harness.files)}")
    print(f"    build: cd {args.output} && ./build.sh")
    print(f"    run:   cd {args.output} && ./run.sh")
    return 0


def _infer_lang(args) -> str:
    if args.contract: return "solidity"
    if args.spec: return "python"
    if args.source:
        ext = Path(args.source).suffix.lower()
        if ext in (".rs",): return "rust"
        if ext in (".c", ".h"): return "c"
        if ext in (".cpp", ".cc", ".hpp"): return "cpp"
        if ext in (".py",): return "python"
        if ext in (".sol",): return "solidity"
        if ext in (".go",): return "go"
    return "c"


if __name__ == "__main__":
    raise SystemExit(main())
